apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: new-nginx
    type: canary
  name: new-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: new-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: new-nginx
        type: canary
    spec:
      containers:
      - image: nginx:1.14
        name: nginx
        resources: {}
        volumeMounts:
        - name: canvol
          mountPath: /usr/share/nginx/html/
      volumes:
      - name: canvol
        configMap: 
          name: canary   
status: {}
