apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mybusybox
  name: mybusybox
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: busybox
    name: mybusybox
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
