apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-b
  name: pod-b
  namespace: ckad-ns1
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: alpine
    name: alpine
    resources: {}
  - name: nginx
    image: nginx
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
