apiVersion: v1
kind: Pod
metadata:
  name: sidecar-pod
  namespace: ckad-ns3
spec:

  restartPolicy: Never

  volumes:
  - name: shared-data
    hostPath:
      path: /mydata

  containers:

  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html

  - name: busybox-container
    image: busybox
    volumeMounts:
    - name: shared-data
      mountPath: /var/log
    args:
      - sh
      - -c
      - while sleep 5; do date >> /var/log/date.log; done
